-- PostgreSQL port of migrations-sqlite/0001_items.sql (V2 "PostgreSQL
-- アプリ全体対応", PR3). Same columns/names/semantics as the SQLite version;
-- only the types are made strict for Postgres:
--   INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--     (BY DEFAULT, not ALWAYS, so `db::seed_if_empty` can insert its explicit
--      1..N ids; the identity sequence is advanced past the seed afterward).
--   INTEGER (i64 in Rust) -> BIGINT, so sqlx decodes `id`/`price`/`stock` into
--     `i64` without an INT4/INT8 mismatch.
--   `updated_at` stays TEXT: the app writes/reads it as a `YYYY-MM-DD` string
--     (`items` decodes it into `String`), never as a native date.
CREATE TABLE items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price BIGINT NOT NULL,
    stock BIGINT NOT NULL,
    updated_at TEXT NOT NULL
);
