-- PostgreSQL port of migrations-sqlite/0003_users.sql. Type mapping:
--   INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--     (id decodes into i64; BY DEFAULT for symmetry with the other tables).
--   created_at/updated_at stay TEXT (the app decodes them into `String`), so
--     the SQLite `DEFAULT (datetime('now'))` becomes `DEFAULT (now()::text)`:
--     a bare `DEFAULT now()` would be `timestamptz` and Postgres has no
--     implicit assignment cast from timestamptz to text, so the cast is
--     required. The stored string's shape differs from SQLite's
--     `YYYY-MM-DD HH:MM:SS` (Postgres includes fractional seconds + offset),
--     but these columns are display-only snapshots; no logic parses them.
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    display_name TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (now()::text),
    updated_at TEXT NOT NULL DEFAULT (now()::text)
);
