-- PostgreSQL port of migrations-sqlite/0006_attachments.sql. Type mapping:
--   INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY.
--   size_bytes INTEGER (i64 in Rust) -> BIGINT.
--   has_thumbnail INTEGER (0/1 bool stand-in) -> BOOLEAN (AttachmentMeta
--     decodes it into `bool`). Because this column is a real BOOLEAN, the
--     `banto-attachments` write path emits the boolean literals FALSE/TRUE on
--     Postgres (0/1 on SQLite) - integer 0/1 would not implicitly cast to
--     BOOLEAN in Postgres.
--   created_at stays TEXT (an ISO-8601 UTC string written by the crate, e.g.
--     "2026-07-15T12:34:56Z"); no native timestamp type is used.
--
-- M20: generic file/image attachments (spec docs/attachments-plan.md §3.2).
-- Deliberately NOT added to backup.rs's REQUIRED_TABLES so an older backup
-- taken before this migration existed stays restorable.
CREATE TABLE attachments (
  id            BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resource      TEXT    NOT NULL,           -- e.g. 'items'
  resource_id   TEXT    NOT NULL,           -- TEXT for resource-agnosticism; items stringifies its i64 id
  file_name     TEXT    NOT NULL,           -- original display name; never used to build a filesystem path
  mime          TEXT    NOT NULL,           -- normalized from magic-byte detection, not client-supplied
  size_bytes    BIGINT  NOT NULL,
  sha256        TEXT    NOT NULL,           -- integrity check / future dedup use
  has_thumbnail BOOLEAN NOT NULL DEFAULT FALSE,
  created_at    TEXT    NOT NULL,           -- ISO 8601 UTC, e.g. "2026-07-15T12:34:56Z"
  created_by    TEXT                        -- username snapshot, display only (audit already owns the real trail)
);
CREATE INDEX idx_attachments_record ON attachments(resource, resource_id);
