-- PostgreSQL port of migrations-sqlite/0007_customers.sql（conventions §11:
-- 同一スキーマの Postgres 厳密型版。列名・意味は SQLite 版と同一）。
--   INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   INTEGER（Rust の i64） -> BIGINT（sqlx が INT4/INT8 の不一致を起こさないため）
--   created_at / updated_at は TEXT のまま（アプリが YYYY-MM-DD 文字列として
--     読み書きするため。items の updated_at と同じ扱い）
CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    contact_person TEXT,
    address TEXT,
    phone TEXT,
    email TEXT,
    billing_name TEXT,
    closing_day BIGINT NOT NULL,
    payment_month_offset BIGINT NOT NULL,
    payment_day BIGINT NOT NULL,
    note TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);
