-- PostgreSQL port of migrations-sqlite/0008_projects.sql（conventions §11）。
--   INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   金額・外部キーの INTEGER -> BIGINT（Rust 側は i64 / Option<i64>）
--   日付列（started_on / due_on）は TEXT のまま: 業務日付を JST の
--     YYYY-MM-DD 文字列として保持する規約（CLAUDE.md 第4章）に従い、
--     ネイティブ date 型にしない
CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    customer_id BIGINT NOT NULL REFERENCES customers(id),
    name TEXT NOT NULL,
    status TEXT NOT NULL,
    started_on TEXT,
    due_on TEXT,
    estimate_amount BIGINT,
    contract_amount BIGINT,
    scope TEXT,
    note TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX idx_projects_customer ON projects(customer_id);
CREATE INDEX idx_projects_status ON projects(status);
