-- PostgreSQL port of migrations-sqlite/0012_trips.sql（conventions §11）。
--   INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   外部キー・日数の INTEGER -> BIGINT
--   start_on / end_on は TEXT のまま（業務日付は JST の YYYY-MM-DD 文字列）
CREATE TABLE trips (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id),
    destination TEXT NOT NULL,
    start_on TEXT NOT NULL,
    end_on TEXT NOT NULL,
    onsite_days BIGINT NOT NULL,
    nights BIGINT NOT NULL,
    note TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX idx_trips_project ON trips(project_id);
