-- PostgreSQL port of migrations-sqlite/0013_work_logs.sql（conventions §11）。
--   INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   金額（applied_rate / internal_cost）・分・外部キーの INTEGER -> BIGINT
--   worked_on は TEXT のまま（業務日付は JST の YYYY-MM-DD 文字列）
--   applied_rate に cost_rates への外部キーを張らない点も SQLite 版と同じ
--   （スナップショット列。CLAUDE.md 第5章）
CREATE TABLE work_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id),
    trip_id BIGINT REFERENCES trips(id) ON DELETE SET NULL,
    worked_on TEXT NOT NULL,
    work_category_code TEXT NOT NULL,
    minutes BIGINT NOT NULL,
    applied_rate BIGINT NOT NULL,
    internal_cost BIGINT NOT NULL,
    description TEXT,
    invoiced BIGINT NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX idx_work_logs_project ON work_logs(project_id, worked_on);
CREATE INDEX idx_work_logs_trip ON work_logs(trip_id);
