-- PostgreSQL port of migrations-sqlite/0014_expenses.sql（conventions §11）。
--   INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   金額・外部キー・真偽値の INTEGER -> BIGINT
--   spent_on は TEXT のまま（業務日付は JST の YYYY-MM-DD 文字列）
CREATE TABLE expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id),
    trip_id BIGINT REFERENCES trips(id) ON DELETE SET NULL,
    spent_on TEXT NOT NULL,
    expense_category_code TEXT NOT NULL,
    payee TEXT,
    amount BIGINT NOT NULL,
    tax_category TEXT NOT NULL,
    description TEXT,
    billable BIGINT NOT NULL DEFAULT 0,
    invoiced BIGINT NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX idx_expenses_project ON expenses(project_id, spent_on);
CREATE INDEX idx_expenses_trip ON expenses(trip_id);
