-- PostgreSQL port of migrations-sqlite/0015_invoices.sql（conventions §11）。
--   INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   金額・外部キーの INTEGER -> BIGINT
--   業務日付（issued_on / closing_on / due_on）は TEXT のまま
CREATE TABLE invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number TEXT UNIQUE,
    customer_id BIGINT NOT NULL REFERENCES customers(id),
    status TEXT NOT NULL,
    issued_on TEXT,
    closing_on TEXT,
    due_on TEXT,
    corrected_invoice_id BIGINT,
    total_taxable BIGINT NOT NULL DEFAULT 0,
    total_tax BIGINT NOT NULL DEFAULT 0,
    total_amount BIGINT NOT NULL DEFAULT 0,
    rounding_mode TEXT NOT NULL,
    issuer_name TEXT,
    issuer_registration_number TEXT,
    issuer_address TEXT,
    note TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX idx_invoices_customer ON invoices(customer_id, issued_on);
CREATE INDEX idx_invoices_status ON invoices(status);
