-- PostgreSQL port of migrations-sqlite/0016_invoice_lines.sql（conventions §11）。
--   INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   金額・数量・外部キーの INTEGER -> BIGINT
CREATE TABLE invoice_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
    project_id BIGINT NOT NULL,
    line_no BIGINT NOT NULL,
    item_name TEXT NOT NULL,
    quantity BIGINT NOT NULL DEFAULT 1,
    unit_price BIGINT NOT NULL,
    amount BIGINT NOT NULL,
    tax_category TEXT NOT NULL,
    source_type TEXT,
    source_id BIGINT,
    note TEXT
);

CREATE INDEX idx_invoice_lines_invoice ON invoice_lines(invoice_id, line_no);
CREATE INDEX idx_invoice_lines_project ON invoice_lines(project_id);
