-- PostgreSQL port of migrations-sqlite/0017_invoice_tax_summaries.sql（conventions §11）。
--   INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   金額・率（basis point）・外部キーの INTEGER -> BIGINT
CREATE TABLE invoice_tax_summaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
    tax_category TEXT NOT NULL,
    rate_bp BIGINT NOT NULL,
    taxable_amount BIGINT NOT NULL,
    tax_amount BIGINT NOT NULL
);

CREATE INDEX idx_invoice_tax_summaries_invoice ON invoice_tax_summaries(invoice_id);
