-- PostgreSQL port of migrations-sqlite/0019_payments.sql（conventions §11）。
--   INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   金額・外部キーの INTEGER -> BIGINT
--   paid_on は TEXT のまま（業務日付は JST の YYYY-MM-DD 文字列）
CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers(id),
    paid_on TEXT NOT NULL,
    amount BIGINT NOT NULL,
    method TEXT,
    note TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX idx_payments_customer ON payments(customer_id, paid_on);
