-- PostgreSQL port of migrations-sqlite/0022_sync_tables.sql（conventions §11）。
--   INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   seq / peer_device_id / *_through_seq の INTEGER -> BIGINT
--   changed_at / last_synced_at は TEXT のまま（SQLite と同じ ISO 文字列）
CREATE TABLE sync_outbox (
    seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name TEXT NOT NULL,
    row_key TEXT NOT NULL,
    op TEXT NOT NULL,
    changed_at TEXT NOT NULL
);

CREATE INDEX idx_sync_outbox_row ON sync_outbox (table_name, row_key);

CREATE TABLE sync_state (
    peer_device_id BIGINT PRIMARY KEY,
    sent_through_seq BIGINT NOT NULL DEFAULT 0,
    received_through_seq BIGINT NOT NULL DEFAULT 0,
    last_synced_at TEXT
);
