-- PostgreSQL port of migrations-sqlite/0025_sync_conflicts.sql（conventions §11）。
--   INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   peer_device_id の INTEGER -> BIGINT
--   detected_at / resolved_at は TEXT のまま（`sync::now_text_expr` が両方言で
--   TEXT を返す。`Dialect::now_expr` の timestamptz は TEXT 列へ入らない）
CREATE TABLE sync_conflicts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    peer_device_id BIGINT NOT NULL,
    table_name TEXT NOT NULL,
    row_key TEXT NOT NULL,
    reason TEXT NOT NULL,
    local_row TEXT NOT NULL,
    incoming_row TEXT NOT NULL,
    detected_at TEXT NOT NULL,
    resolved_at TEXT
);

CREATE INDEX idx_sync_conflicts_open ON sync_conflicts (resolved_at, table_name, row_key);
